# docker-compose.dev.yml
version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Footy2025!
      MYSQL_DATABASE: footysim
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql+aiomysql://root:root@db:3306/footysim
      PYTHONPATH: src
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src:rw
      - ./requirements.txt:/app/requirements.txt:ro
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
